---
title: "Product values"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# PACKAGES

```{r message=FALSE, warning=FALSE}
rm(list = ls())

library(glue)
library(readxl)
library(lubridate)
library(tidyverse)
library(anytime)
```


# GENERAL INSURANCE

## Statements

```{r}
gi_stmts_1 <-
readxl::read_xls("../../../../../../Sudan/GI/gi_policy_statement_sudan.xls", sheet = 1) %>%
  mutate (TRANSACTION_DATE = as.Date(TRANSACTION_DATE, origin="1899-12-30"))

gi_stmts_2 <-
readxl::read_xls("../../../../../../Sudan/GI/gi_policy_statement_sudan.xls", sheet = 2)  %>%
  mutate (TRANSACTION_DATE = as.Date(TRANSACTION_DATE, origin="1899-12-30"))
```


```{r}
general_statements_raw <- 
  bind_rows(gi_stmts_1,
            gi_stmts_2) 
```

"Create Policy" is when a policy is bought.

```{r}
general_statements_raw %>% 
  filter(AMOUNT > 0) %>% 
  count(TRANSACTION_TYPE)
```

## Products

Product names with policy number.

```{r}
general_products <-
read_excel("../../../../../../Sudan/GI/policyheader_nonlife_sudan.xls") %>% 
  filter(!is.na(ACCOUNT_NO)) %>%
  select(POLICY_NO, POLICY_TYPE) 

general_products
```

```{r}
length(intersect(general_products$POLICY_NO, general_statements_raw$POLICY_NO))
```
## Product values

```{r}
general_product_values <-
general_statements_raw %>% 
  filter(AMOUNT > 0) %>% 
  # filter(TRANSACTION_TYPE == "Create Policy") %>% 
  filter(TRANSACTION_DATE >= "2018-01-01") %>% 
  left_join(general_products, by = "POLICY_NO") %>% 
  select(POLICY_TYPE, AMOUNT) %>% 
  group_by(POLICY_TYPE) %>% 
  summarise(product_value = round(mean(AMOUNT)),
            accounts = n()) %>% 
  rename(PRODUCT = POLICY_TYPE)

general_product_values
```

# ALL PRODUCTS

```{r}
product_values <- 
      general_product_values

product_values
```


# MISSING

Check that all products have assigned product values and impute.

```{r}
product_businesslines <-
readRDS(file = "../outputs/product_businesslines.rds")

product_businesslines
```


```{r}
product_businesslines %>% 
  left_join(product_values) %>% 
  filter(is.na(product_value))
```


```{r}
product_values <-
product_businesslines %>% 
  left_join(product_values, by = "PRODUCT") %>% 
  group_by(BUSINESS_LINE) %>%
  mutate(product_value = replace_na(product_value, 
                                    mean(product_value, na.rm = TRUE))) %>% 
  ungroup() %>%
  mutate(product_value = if_else(condition = is.nan(product_value), 
                                 true = 99999, 
                                 false = product_value)) %>% 
  mutate(product_value = round(product_value)) %>% 
  select(-BUSINESS_LINE)

product_values 
```

# EXPORT

```{r}
save.image("../outputs/23June_Product_Values.RData")
#load("../outputs/16May_Product_Values.RData")

saveRDS(product_values,"../outputs/product_values.rds")
```

