---
title: "Cross-sell Model"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(recommenderlab)
library(tidyverse)
```


# Import Data

```{r}
asset_product_holding <- readRDS(file = "../../01. Determine product holding/outputs/objects/asset_product_holding.rds")

life_product_holding <- readRDS(file = "../../01. Determine product holding/outputs/objects/life_product_holding.rds")
```



# Merge the tables

```{r}
products_df_raw <-
asset_product_holding %>% 
  rename(ACCOUNT_NO = ACCOUNT_NUMBER) %>% 
  bind_rows(life_product_holding %>% 
              rename(ACCOUNT_NO = CUSTOMER_NUMBER))

dim(products_df_raw)
products_df_raw
```

# Overall product holding

On average, people purchase just one product.

```{r}
products_df_raw %>% 
  count(ACCOUNT_NO) %>% 
  summary()
```

```{r}
purchase_dist <-
products_df_raw %>% 
  count(ACCOUNT_NO) %>% 
  mutate(n = pmin(2, n)) %>% 
  ggplot(aes(n))+
  geom_histogram(binwidth = 0.5)+
  #scale_y_log10(labels = scales::comma_format())+
  scale_x_continuous(breaks = c(1,2),
                     labels = c(1,"+2"))+
  stat_bin(binwidth=1, geom="text", aes(label=..count..), vjust=0.25)+
  labs(title = "Distribution of product purchases",
       x = "Purchases",
       y = "Purchase Frequency")

purchase_dist
```


# Create dummy variables

```{r}
products_df <-
products_df_raw %>% 
  pivot_wider(names_from = PRODUCT, 
              values_from = n, 
              values_fill = 0)

dim(products_df)
head(products_df)
```


# Missing account numbers

```{r}
setdiff(x = asset_product_holding$ACCOUNT_NO, 
        y = products_df$ACCOUNT_NO)

setdiff(x = life_product_holding$ACCOUNT_NO, 
        y = products_df$ACCOUNT_NO)
```


# Convert to matrix

```{r}
products_matrix <-
products_df %>% 
  select(-ACCOUNT_NO) %>% 
  as.matrix()

rownames(products_matrix) <- products_df %>% pull(ACCOUNT_NO)
```

# Check matrix

```{r}
rownames(products_matrix)[1:10]
colnames(products_matrix)
```


# Convert to binaryRatingMatrix

```{r}
products_rating_matrix <- as(products_matrix, "binaryRatingMatrix")
```


```{r}
class(products_rating_matrix)
```

# Notes

It should be indicated on the app that:
* Asset Mgt: Account No = ACCOUNT_NUMBER
* Life Ins: Account No = CUSTOMER_NUMBER

# Export

```{r}
saveRDS(object = products_rating_matrix, 
        file = "../outputs/products_rating_matrix.rds")

save.image("./05May_RatingMatrix.RData")
#load("./20Apr_RatingMatrix.RData")
```

