---
title: "Product values"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# PACKAGES

```{r message=FALSE, warning=FALSE}
rm(list = ls())

library(readxl)
library(lubridate)
library(tidyverse)
```


# PRODUCT BUSINESS LINES

```{r}
product_businesslines <- readRDS("../outputs/product_businesslines.rds")

product_businesslines
```

# HEALTH INSURANCE

## Product values

```{r}
health_product_values <-
read_excel("../../../../../../Uganda/Health/ug_product_values.xlsx") %>%
  rename (product_value = Values) %>% 
  mutate (accounts = 99999) 

health_product_values
```

# GENERAL INSURANCE


```{r}
gi_statement_raw <- readRDS(file = "../../product_holding/gi_statement_raw.rds")
gi_products_raw <- readRDS(file = "../../product_holding/gi_products_raw.rds") %>% 
  as_tibble()
```

```{r}
gi_products_raw
```


```{r}
gi_product_values <-
gi_statement_raw %>% 
  left_join(gi_products_raw %>% 
              select(POLICY_NO, POLICY_TYPE), 
            by = "POLICY_NO") %>% 
  mutate(AMOUNT = as.numeric(AMOUNT)) %>% 
  group_by(POLICY_TYPE) %>% 
  summarise(product_value = mean(AMOUNT),
            accounts = n()) %>% 
  rename(PRODUCT = POLICY_TYPE)

gi_product_values
```

# ALL PRODUCTS

```{r}
product_values_raw <-
rbind(health_product_values,
      gi_product_values)

product_values_raw
```


# MISSING

Check that all products have assigned product values and impute.

```{r}
product_businesslines %>% 
  left_join(product_values_raw) %>% 
  filter(is.na(product_value))
```


```{r}
product_values <-
product_businesslines %>% 
  left_join(product_values_raw, by = "PRODUCT") %>% 
  group_by(BUSINESS_LINE) %>%
  mutate(product_value = replace_na(product_value, 
                                    mean(product_value, na.rm = TRUE))) %>% 
  ungroup() %>%
  mutate(product_value = if_else(condition = is.nan(product_value), 
                                 true = 99999, 
                                 false = product_value)) %>% 
  mutate(product_value = round(product_value)) %>% 
  select(-BUSINESS_LINE)

product_values 
```

# EXPORT

```{r}
save.image("../outputs/7June_Product_Values.RData")
#load("../outputs/16May_Product_Values.RData")

saveRDS(product_values,"../outputs/product_values.rds")
```