---
title: "Product-Customer Matching"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# PACKAGES

```{r message=FALSE, warning=FALSE}
rm(list = ls())

library(readxl)
library(data.table)
library(tidyverse)
```

# LIFE INSURANCE

## Data exploration

Life insurance products

```{r}
life_products_raw <-
read_csv(file = "../../../../../../Ghana/Life/POLICY_HEADER.csv") %>% 
  unite(col = PRODUCT, c(CONTRACT_GROUP_NAME), sep = "_") %>% 
  select(ACCOUNT_NUMBER, PRODUCT) %>% 
  mutate(PRODUCT = str_remove(string = PRODUCT, pattern = "_NA$")) %>%
  mutate_at("ACCOUNT_NUMBER", str_replace, "\\(", "") %>%
  mutate_at("ACCOUNT_NUMBER", str_replace, "\\+", "") %>%
  filter(str_length(ACCOUNT_NUMBER) > 0) %>%
  filter(!is.na(ACCOUNT_NUMBER))

(life_products_raw)
```


```{r}
life_products <- 
  read_csv(file = "../../../../../../Ghana/Life/POLICY_HEADER.csv") %>% 
    select(ACCOUNT_NUMBER, CONTRACT_GROUP_NAME, AGENT_CONTRACT_ID, CONTRACT_ID) %>%
    mutate_at("ACCOUNT_NUMBER", str_replace, "\\(", "") %>%
    mutate_at("ACCOUNT_NUMBER", str_replace, "\\+", "")

life_products
```


`CUSTOMER_NUMBER` is the unique customer identifier.

## Product holding

```{r}
life_product_holding <-
life_products_raw %>% 
  distinct(ACCOUNT_NUMBER, PRODUCT) %>% 
  add_count(ACCOUNT_NUMBER, PRODUCT)

life_product_holding
```
## Sense check

Check NAs

```{r}
life_product_holding %>% distinct(PRODUCT)

life_product_holding %>% filter(str_detect(ACCOUNT_NUMBER,"NA"))
```


Check each product is mapped once per customer.

```{r}
unique(life_product_holding$n)
```
Check that a customer can have many products under them.

```{r}
life_product_holding %>% 
  count(ACCOUNT_NUMBER, sort = TRUE)
```

Number of products

```{r}
insufficient_life_purchases <-
life_products_raw %>% 
  count(PRODUCT) %>% 
  filter(n<23) %>% 
  pull(PRODUCT)

life_product_holding <- 
  life_product_holding %>% 
    filter(!PRODUCT %in% insufficient_life_purchases)
```



# EXPORT

```{r}
#dir.create("../outputs/objects", recursive = TRUE)
save.image(file = "./7June.RData")

saveRDS(object = life_product_holding, 
        file = "../../product_holding/life_product_holding.rds")

saveRDS(object = life_products,
        file = "../../product_holding/life_products.rds")

load("./7June.RData")
```









