---
title: "Product values"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# PACKAGES

```{r message=FALSE, warning=FALSE}
rm(list = ls())

library(glue)
library(readxl)
library(lubridate)
library(tidyverse)
```

# LIFE INSURANCE

## Statements

```{r}
life_statements_raw <-
read.csv("../../../../../../Ghana/Life/LIFE_TRANSACTION_HISTORY.csv") %>% 
  select(DATE, CONTRACT_ID, INVESTED_PREMIUM)
```

Date filter was removed because it resulted in very few products being retained.

```{r}
life_statements <- life_statements_raw %>%
  filter(INVESTED_PREMIUM > 0)

life_statements
```

## Products

Product names with policy number.

```{r}
life_products <- readRDS("../../product_holding/life_products.rds")

life_products
```

## Product values

```{r}
life_product_values <-
life_statements %>% 
  left_join(life_products, by = "CONTRACT_ID") %>% 
  select(CONTRACT_GROUP_NAME, INVESTED_PREMIUM) %>% 
  group_by(CONTRACT_GROUP_NAME) %>% 
  summarise(product_value = mean(INVESTED_PREMIUM),
            accounts = n()) %>% 
  filter(!is.na(CONTRACT_GROUP_NAME)) %>% 
  rename(PRODUCT = CONTRACT_GROUP_NAME)

life_product_values
```


# ALL PRODUCTS

```{r}
product_values <- life_product_values

product_values
```


# MISSING

Check that all products have assigned product values and impute.

```{r}
product_businesslines <-
readRDS(file = "../outputs/product_businesslines.rds")

product_businesslines
```


```{r}
product_businesslines %>% 
  left_join(product_values) %>% 
  filter(is.na(product_value))
```


```{r}
product_values <-
product_businesslines %>% 
  left_join(product_values, by = "PRODUCT") %>% 
  group_by(BUSINESS_LINE) %>%
  mutate(product_value = replace_na(product_value, 
                                    mean(product_value, na.rm = TRUE))) %>% 
  ungroup() %>%
  mutate(product_value = if_else(condition = is.nan(product_value), 
                                 true = 99999, 
                                 false = product_value)) %>% 
  mutate(product_value = round(product_value)) %>% 
  select(-BUSINESS_LINE)

product_values 
```

# EXPORT

```{r}
save.image("../outputs/10June_Product_Values.RData")
#load("../outputs/16May_Product_Values.RData")

saveRDS(product_values,"../outputs/product_values.rds")
```